name: metocean-api
channels:
  - conda-forge
dependencies:
  - python=>3.9
  - matplotlib>=3.1
  - numpy>=1.17
  - pandas
  - xarray
  - dask
  - pip
  - nco
  - pynco
  - netcdf4
  - time
  - pytest
