name: metocean-api
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - matplotlib>=3.1
  - numpy>=1.17
  - pandas
  - xarray
  - dask>=2024.9.1
  - pip
  - netcdf4
  - pytest
  - pytest-cov
  - cdsapi
  - cartopy
  - setuptools
  - metpy
  - tqdm
  - cfgrib
